name: 🔨 Build Test
on:
  push:
  pull_request:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build gsolc-select
        run: go build .
        working-directory: cmd/gsolc-select/

      - name: Build solc
        run: go build .
        working-directory: cmd/solc/

      - name: Test
        run: go test ./...
        working-directory: .
